server:
  port: 8001
spring:
  main:
    allow-bean-definition-overriding: true
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: yyy-eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
ribbon:
  eureka:
    enabled: true
